### PR TITLE
Change license to Apache 2.0

### PR DESCRIPTION
**Pull request by kaplanlior**
Hi,

Per discussion I had with @omerpines, we start aligning the licenses for the Midburn sub projects.

In order align the license to Apache 2.0, please approve this PR by commenting bellow agreeing to the change.

@eyalliebermann @guywarburg @mbenarie @noamr

### CODE REVIEW

**Comment by kaplanlior** [comment]
I want everyone to approve the change... same as agreeing to the new license.

**Comment by noamr** [comment]
Ah ok, sorry. It seems like this was agreed on on #general slack.

**Comment by eyalliebermann** [comment]
Cool.
license is now Apache 2.0

**Comment by mbenarie** [comment]
👍

**Pull request merged**
